### PR TITLE
fix(cnpg-backup): BREAKING CHANGE allow toggling encryption

### LINKED ISSUE #849: Support the disable of  server side encryption for cnpg cluster
### Is your feature request related to a problem?

I want to backup cnpg cluster to minio s3 but the default config try to do server side encryption in my bucket and i don't have in minio, by default it try encryption

### Describe the solution you'd like

Permit to do variables or disable wal encryption 
https://github.com/truecharts/library-charts/blob/main/library/common/templates/lib/cnpg/cluster/_backup.tpl

```
  barmanObjectStore:
    wal:
      encryption: AES256
    data:
      encryption: AES256
```

the minio documentation about KES/KVM 
https://min.io/docs/minio/linux/operations/server-side-encryption.html#minio-sse-data-encryption

with cnpg documentation
https://cloudnative-pg.io/documentation/1.23/wal_archiving/#wal-archiving

### Describe alternatives you've considered

I manualy remove `encryption: AES256` in my cluster

### Additional context

_No response_

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### PR DESCRIPTION
**Pull request by stavros-k**
**Description**

⚒️ Fixes  #849 

**⚙️ Type of change**

- [ ] ⚙️ Feature/App addition
- [x] 🪛 Bugfix
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🔃 Refactor of current code

**🧪 How Has This Been Tested?**

**📃 Notes:**

**✔️ Checklist:**

- [x] ⚖️ My code follows the style guidelines of this project
- [x] 👀 I have performed a self-review of my own code
- [ ] #️⃣ I have commented my code, particularly in hard-to-understand areas
- [ ] 📄 I have made corresponding changes to the documentation
- [x] ⚠️ My changes generate no new warnings
- [x] 🧪 I have added tests to this description that prove my fix is effective or that my feature works
- [x] ⬆️ I increased versions for any altered app according to semantic versioning
- [x] I made sure the title starts with `feat(chart-name):`, `fix(chart-name):` or `chore(chart-name):`

**➕ App addition**

If this PR is an app addition please make sure you have done the following.

- [ ] 🖼️ I have added an icon in the Chart's root directory called `icon.png`

---

_Please don't blindly check all the boxes. Read them and only check those that apply.
Those checkboxes are there for the reviewer to see what is this all about and
the status of this PR with a quick glance._

### CODE REVIEW

**Comment by stavros-k** [comment]
This also fixes a behavior change that currently only in helm unittest appears.
But helm will also update the underlying package later.

The change made is backwards compatible for all versions

Previously:

`camelcase` capitalized the first letter as well.

Now it lowercases the first letter (which is what it shuld do in the first place)

so we now `camecase` it and then `title` it, which gives the expected result.

**Comment by stavros-k** [comment]
@PrivatePuffin  Should we default to enabled encryption for backwards compat?

**Comment by PrivatePuffin** [comment]
> @PrivatePuffin Should we default to enabled encryption for backwards compat?

I think it might be best to default to no encryption for both volsync and cnpg, to give things similar.

**Comment by stavros-k** [comment]
> > @PrivatePuffin Should we default to enabled encryption for backwards compat?
> 
> I think it might be best to default to no encryption for both volsync and cnpg, to give things similar.

Hmm, I can't seem to find the encrypting in volsync at least not in our templates. Can you link to it?

**Comment by stavros-k** [comment]
Then this can be moved forward? Is there anything else to do here?

**Review by PrivatePuffin — APPROVED** [review]

**Pull request merged**
