### PR TITLE
feat(common): implement support for registering and verifying dynamic operator namespaces

### PR DESCRIPTION
**Pull request by Ornias1993**
**Description**
We got requests from iX that they would like us to not side-load operators into namespaces that are not SCALE managed.
This feature limits allows us to use dynamically named namespaces for charts containing operators.

It registers all operators and their namespace using a configmap in the fixed `tc-system` namespace.

This means all operators can use dynamic namespaces (if the operator itself supports that) and don't have to be hotloaded in non-scale namespaces by manifestmanager in the future anymore.

It also moves tc-system namespace creation to common.
This ensures we can also change traefik middleware namespace logic later as well.

On top of this, it also contains logic to prevent duplicate installs of the same operator.

**⚙️ Type of change**

- [x] ⚙️ Feature/App addition
- [ ] 🪛 Bugfix
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🔃 Refactor of current code

**🧪 How Has This Been Tested?**

**📃 Notes:**

**✔️ Checklist:**

- [x] ⚖️ My code follows the style guidelines of this project
- [x] 👀 I have performed a self-review of my own code
- [x] #️⃣ I have commented my code, particularly in hard-to-understand areas
- [x] 📄 I have made corresponding changes to the documentation
- [x] ⚠️ My changes generate no new warnings
- [x] 🧪 I have added tests to this description that prove my fix is effective or that my feature works
- [x] ⬆️ I increased versions for any altered app according to semantic versioning

**➕ App addition**

If this PR is an app addition please make sure you have done the following.

- [ ] 🪞 I have opened a PR on [truecharts/containers](https://github.com/truecharts/containers) adding the container to TrueCharts mirror repo.
- [ ] 🖼️ I have added an icon in the Chart's root directory called `icon.png`

---

_Please don't blindly check all the boxes. Read them and only check those that apply.
Those checkboxes are there for the reviewer to see what is this all about and
the status of this PR with a quick glance._

### CODE REVIEW

**Comment by Ornias1993** [comment]
PR waiting for @stavros-k to get some unittests fixed/added :)

**Comment by stavros-k** [comment]
- [x] Extended ConfigMap and Secret class to conditionally add `namespace`
- [x] Adapted `_register_operator.tpl` to use the ConfigMap class
- [x] Made Namespace creation conditional (Default to `true`)
        This is mostly to make testing much easier (disable for all tests and only enable for 1 test targeted on this
- [x] Moved Namespace include after `init` in order to be able to access the `.Values.globe.createTCNamespace`
- [x] Formatted the new files a bit
- [x] Cleanup couple other tests while looking on some other things

**Comment by stavros-k** [comment]
https://github.com/truecharts/website/pull/200

**Comment by Ornias1993** [comment]
Thanks for the hard work on getting this even nicer :-D

**Pull request merged**
