### PR TITLE
feat(mongodb): Init work to integrate mongodb to common

### PR DESCRIPTION
**Pull request by stavros-k**

### CODE REVIEW

**Comment by stavros-k** [comment]
I'm not sure why or if we need both `plain` and `plainhost` as they are exactly the same.
(Same applies to `mariadb`,`redis` and `postgres`).

**Comment by stavros-k** [comment]
I think this should be close to "ready".

Am I forgetting any other place I should "add" mongodb?

**Comment by Ornias1993** [comment]
> * I'm not sure why or if we need both `plain` and `plainhost` as they are exactly the same.
>   (Same applies to `mariadb`,`redis` and `postgres`).

- I think I wanted to simplify it but we had some legacy.
Feel free to keep this and i'll add it to the refactor todo

> * All image references to dependecies are to `ghcr`. Is that on purpose or we should change it to `tccr`?

Keep it at ghcr for now, there where issues with SCARF.
It's on my TODO list to test if we can move these to TCCR anytime soon.

**Review by Ornias1993 — CHANGES_REQUESTED** [review]
Can i have a bump please?
minor ofc.

Don't see any other obvious issues, nice build.
Also great verification thingy.

**Comment by Ornias1993** [comment]
Bumped

**Comment by Ornias1993** [comment]
I'm going to merge this, as the only same way of testing this would be having it pass the CI on an App.
And it also shouldn't cause issues with Apps not using MongoDB anyway...

**Pull request merged**
