### PR TITLE
Re-add vpn additionalVolumeMounts

### PR DESCRIPTION
**Pull request by varac**
**Description**

This PR re-adds the `addons.vpn.additionalVolumeMounts` key so users have the possibility to mount arbitrary Volumes.

**⚙️ Type of change**

- [x] ⚙️ Feature/App addition
- [ ] 🪛 Bugfix
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🔃 Refactor of current code

**🧪 How Has This Been Tested?**

I used my branch of the common library chart together with the transmission chart like this:

```
❯ gd
diff --git a/charts/stable/transmission/Chart.yaml b/charts/stable/transmission/Chart.yaml
index 8761dc5b6b..381760b2b4 100644
--- a/charts/stable/transmission/Chart.yaml
+++ b/charts/stable/transmission/Chart.yaml
@@ -2,8 +2,9 @@ apiVersion: v2
 appVersion: "3.00"
 dependencies:
   - name: common
-    repository: https://library-charts.truecharts.org
-    version: 10.8.1
+    # repository: https://library-charts.truecharts.org
+    repository: "file://../../../../library-charts/charts/common"
+    version: 10.8.2
 deprecated: false
 description: fast, easy, and free BitTorrent client.
 home: https://truecharts.org/docs/charts/stable/transmission

❯ cat test.yml 
addons:
  vpn:
    type: wireguard
    additionalVolumeMounts:
      - mountPath: /foo
        name: foo

❯ helm template -f test.yml . | grep -B5 foo
          volumeMounts:
          - mountPath: /shared
            name: shared
          - mountPath: /etc/wireguard/wg0.conf
            name: vpnconfig
          - mountPath: /foo
            name: foo
```

**✔️ Checklist:**

- [x] ⚖️ My code follows the style guidelines of this project
- [x] 👀 I have performed a self-review of my own code
- [x] #️⃣ I have commented my code, particularly in hard-to-understand areas
- [x] 📄 I have made corresponding changes to the documentation
- [x] ⚠️ My changes generate no new warnings
- [ ] 🧪 I have added tests to this description that prove my fix is effective or that my feature works
- [x] ⬆️ I increased versions for any altered app according to semantic versioning

### CODE REVIEW

**Comment by Ornias1993** [comment]
We're not going to expose this on the SCALE GUI and have deprecated native-helm support, so I don't really see a usecase for this...

**Comment by Ornias1993** [comment]
Also:
The VPN adding is getting refactored and mostly deleted within a relatively short timeframe

**Comment by varac** [comment]
> We're not going to expose this on the SCALE GUI and have deprecated native-helm support, so I don't really see a usecase for this...

Fair enough, I was wondering about this. Still it would be a nice addition for those who use your charts independent of ScaleUI.

> The VPN adding is getting refactored and mostly deleted within a relatively short timeframe

@Ornias1993 Ok, can you please share details what's refactored and what's going to get removed, so I can judge if it's worth sticking to the chart or not ? Thanks !

**Comment by Ornias1993** [comment]
> > We're not going to expose this on the SCALE GUI and have deprecated native-helm support, so I don't really see a usecase for this...
> 
> Fair enough, I was wondering about this. Still it would be a nice addition for those who use your charts independent of ScaleUI.

To be clear: All support for non-scale UI deployments (aka native helm) is depricated and the helm-charts are not being build anymore as well. (at least for the time being)

> > The VPN adding is getting refactored and mostly deleted within a relatively short timeframe
> 
> @Ornias1993 Ok, can you please share details what's refactored and what's going to get removed, so I can judge if it's worth sticking to the chart or not ? Thanks !

Nope, I currently cannot. It's still under deliberation.

**Comment by Ornias1993** [comment]
Considering the ongoing refactor of the common chart and our future plans for the VPN addon, i'm going to close this,

**Comment by gclawes** [comment]
With the re-opening of the helm repo, it would be useful to have this for vpn addon outside of TrueNAS SCALE (vpn credentials in Secrets, for example).  See #323

**Comment by Ornias1993** [comment]
My last comment still applies though...
It was not closed due to closing the helm repo.

**Comment by Ornias1993** [comment]
Also: We cannot even merge this, as the new (yet unreleased) common chart isn't even compattible with this PR.

**Comment by Ornias1993** [comment]
We've added the option to mount a single folder besides the configfile in the refactor.

**Pull request closed without merging**
