### PR TITLE
fix(tailscale): explicitly set TS_KUBE_SECRET to ""

### PR DESCRIPTION
**Pull request by stavros-k**
**Description**

⚒️ Fixes  # 

**⚙️ Type of change**

- [ ] ⚙️ Feature/App addition
- [x] 🪛 Bugfix
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🔃 Refactor of current code

**🧪 How Has This Been Tested?**

**📃 Notes:**

**✔️ Checklist:**

- [x] ⚖️ My code follows the style guidelines of this project
- [x] 👀 I have performed a self-review of my own code
- [ ] #️⃣ I have commented my code, particularly in hard-to-understand areas
- [ ] 📄 I have made corresponding changes to the documentation
- [x] ⚠️ My changes generate no new warnings
- [ ] 🧪 I have added tests to this description that prove my fix is effective or that my feature works
- [x] ⬆️ I increased versions for any altered app according to semantic versioning

**➕ App addition**

If this PR is an app addition please make sure you have done the following.

- [ ] 🪞 I have opened a PR on [truecharts/containers](https://github.com/truecharts/containers) adding the container to TrueCharts mirror repo.
- [ ] 🖼️ I have added an icon in the Chart's root directory called `icon.png`

---

_Please don't blindly check all the boxes. Read them and only check those that apply.
Those checkboxes are there for the reviewer to see what is this all about and
the status of this PR with a quick glance._

### CODE REVIEW

**Comment by stavros-k** [comment]
Waiting upstream to release the image.

**Review by Ornias1993 — APPROVED** [review]

**Comment by Ornias1993** [comment]
Be sure to ensure it has empty-dir storage attached ;-)

**Comment by andor-pierdelacabeza** [comment]
Ha! I was about to send a patch for this. :)

Installing charts with the tailscale VPN addon is failing right now, as the tailscale client, when running in kubernetes, by default tries to access a secret:

https://github.com/tailscale/tailscale/blob/main/cmd/containerboot/main.go#L41

Then I get an RBAC error:

```
k3s kubectl -n ix-loki logs loki-0 --container tailscale
boot: 2022/12/26 16:13:18 Some Kubernetes permissions are missing, please check your RBAC configuration: multiple errors:
	missing get permission on secret "tailscale"
	missing update permission on secret "tailscale"
```
So, meanwhile, I had to manually edit the statefulSet and add an empty `TS_KUBE_SECRET` env var:

```yaml
        env:
        - name: TS_SOCKET
          value: /var/run/tailscale/tailscaled.sock
        - name: TS_STATE_DIR
          value: /var/lib/tailscale
        - name: TS_AUTH_ONCE
          value: "true"
        - name: TS_USERSPACE
          value: "false"
        - name: TS_ACCEPT_DNS
          value: "false"
        - name: TS_KUBE_SECRET
        envFrom:
        - secretRef:
            name: loki-tailscale-secret
```

Now it works :)

Hope it merges soon!

**Comment by stavros-k** [comment]
> Ha! I was about to send a patch for this. :)
> 
> Installing charts with the tailscale VPN addon is failing right now, as the tailscale client, when running in kubernetes, by default tries to access a secret:
> 
> https://github.com/tailscale/tailscale/blob/main/cmd/containerboot/main.go#L41
> 
> Then I get an RBAC error:
> 
> ```
> k3s kubectl -n ix-loki logs loki-0 --container tailscale
> boot: 2022/12/26 16:13:18 Some Kubernetes permissions are missing, please check your RBAC configuration: multiple errors:
> 	missing get permission on secret "tailscale"
> 	missing update permission on secret "tailscale"
> ```
> 
> So, meanwhile, I had to manually edit the statefulSet and add an empty `TS_KUBE_SECRET` env var:
> 
> ```yaml
>         env:
>         - name: TS_SOCKET
>           value: /var/run/tailscale/tailscaled.sock
>         - name: TS_STATE_DIR
>           value: /var/lib/tailscale
>         - name: TS_AUTH_ONCE
>           value: "true"
>         - name: TS_USERSPACE
>           value: "false"
>         - name: TS_ACCEPT_DNS
>           value: "false"
>         - name: TS_KUBE_SECRET
>         envFrom:
>         - secretRef:
>             name: loki-tailscale-secret
> ```
> 
> Now it works :)
> 
> In theory it should work in v1.34 as it overwrites the default env value: https://github.com/tailscale/tailscale/blob/v1.34.1/cmd/containerboot/main.go#L80
> 
> Hope it merges soon!

Yes, the standalone app does use the secret for state.
But this an addon. While you can make it work with a secret for state, you can't always make sure that a serviceaccount/rbac will be able to be tied to the pod with the correct permissions.
As there are apps that use custom service accounts for their own functionality. Which will make the addon non-functional.
(different access on the serviceaccount/rbac).

Well you might be able to assign merge the rbacs, but then you give access to the TS secret on the main app. etc etc etc.

Once this PR is merged and an image is released, this will be merged.
https://github.com/tailscale/tailscale/pull/6770

**Comment by andor-pierdelacabeza** [comment]
> Yes, the standalone app does use the secret for state.
> But this an addon. While you can make it work with a secret for state, you can't always make sure that a serviceaccount/rbac will be able to be tied to the pod with the correct permissions.
> As there are apps that use custom service accounts for their own functionality. Which will make the addon non-functional.
> (different access on the serviceaccount/rbac).

Ah yes, yes, I meant that. I was adding some context just in case :)

Once this PR is merged and an image is released, this will be merged.
https://github.com/tailscale/tailscale/pull/6770

Seems like I forgot to say that meanwhile I've updated the statefulSet and I'm using [unstable-v1.35](https://hub.docker.com/layers/tailscale/tailscale/unstable-v1.35.100/images/sha256-5ee1819a74b5d55a6519696250dd094b0943fb179931ed0d14488d961cd0d484?context=explore), where it's already fixed. Just in case anyone needs a quick fix.

Thanks!

**Comment by stavros-k** [comment]
Superseded by #292

**Comment by markbergsma** [comment]
I think this may still need an update of the tailscale image to newly released v1.36; the common library is still pinned to v1.34.1.

**Comment by Ornias1993** [comment]
Not relevant.

**Comment by Ornias1993** [comment]
This is an active refactor, please leave it to the maintainers .

**Pull request closed without merging**
